---
- name: Installation of Kuber on Ubuntu and Redhat
  hosts: all
  tasks:
    - name: installing docker on Ubuntu
      apt:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      loop:
        - docker.io
        - apt-transport-https

    - name: adding repo-key on Ubuntu
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - name: adding repo on Ubuntu
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        filename: 'kubernetes'
      when: ansible_distribution == "Ubuntu"


    - name: adding Repo-Key and Repo for RHEl
      yum_repository:
        name: kuber
        description: KubeRepo
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgcheck: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        state: present
      when: ansible_distribution == "RedHat"


    - name: Updating repo
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == "RedHat"

... 

