--- #Handler playbook
- hosts: newserver
  user: ansible1
  become: yes
  connection: ssh

  tasks:
    - name: Installing httpd-server
      action: yum name=httpd state=installed
      notify: restart HTTPD

  handlers:
    - name: restart HTTPD
      action: service name=httpd state=started
