---
- name: installing samba server
  hosts: localhost
  vars_files:
    - /root/ansible/samba/smbvars.yaml
  tasks:
    - name: installing packages
      yum:
        name: "{{item}}"
        state: present
      loop: "{{packages}}"

    - name: create a directory
      file:
        path: /smbshared
        state: directory
        owner: root
        group: root
        mode: '777'

    - name: creating samba group
      group:
        name: smbgrp
        state: present

    - name: create a user
      user:
        name: "{{item}}"
        groups: smbgrp
        append: yes
      loop: "{{users}}"

    - name: Adding into samba user
      shell: '(echo "{{ item.1 }}"; echo "{{ item.1 }}") | smbpasswd -a -s "{{ item.0 }}"'
      with_together:
        - "{{users}}"
        - "{{pass}}"

    - #name: Adding into samba user
      #shell: echo -ne "123\n123\n" | smbpasswd -a -s rohit

    - name: adding content in samba config file
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [tester]
                comment = smb dir for testing team
                path = /smbshared
                valid users = @smbgrp
                write list = viren

    - name: service restart
      service:
        name: "{{item}}"
        state: restarted
      loop: "{{services}}"

    - name: firewall 
      command: "firewall-cmd --permanent --add-service=samba"

    - name: firewall reload
      command: "firewall-cmd --reload"


- hosts: redhat
  vars_files:
    - /root/ansible/samba/sambavars.yaml
  tasks:
    - name: installing packages
      yum:
        name: "{{item}}"
        state: present
      loop: "{{clientpkg}}" 
    
    - name: mounting samba
      file:
        name: /mount_nmb
        state: directory
        owner: root
        group: root
        mode: '0777'

    - name: mounting samba server
      mount:
        src: //172.31.37.153/tester
        path: /mount_smb
        fstype: cifs
        opts: "credentials=/smbcreds,file_mode=0700,root"
        state: mounted

...

