---
- name: W-get playbook
  hosts: all
  tasks:
    - name: downloading kernel package
      get_url:
        url: https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/kernel-4.18.0-305.10.2.el8_4.x86_64.rpm
        dest: /srv
        remote_src: yes
        
